# working biscuit modified go makefile
# assumes go is installed at ~/go
# curl -fsSL -o go.linux-amd64.tar.gz https://go.dev/dl/go1.10.8.linux-amd64.tar.gz && tar -xzf go.linux-amd64.tar.gz

all:
	GOROOT_BOOTSTRAP=~/go GO111MODULE=off ./make.bash
